name: Deploy React My App
on: 
  push:
    branches:
       - 'master' 
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      # - name: Test aplication
        # run: npm run test
  lint:    
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      # - name: Test aplication
        # run: npm run test
  build: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build aplication
        run: npm run build
      - name: Deploy
        run: echo Deploying ...