name: Deploy React My App
on: 
  push:
    branches:
       - 'master' 
    # paths-ignore:
    #    - '.github/workflows/*'   
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pakege-loc.json') }}
      - name: Install dependecies
        run: npm ci
      # - name: Test aplication
        # run: npm run test
  lint:    
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pakege-loc.json') }}
      - name: Install dependecies
        run: npm ci
      # - name: Test aplication
        # run: npm run test
  build: 
    needs: [ lint, test ]
    strategy:
       matrix:
          node-version: [ 14, 16 ]
          os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}      
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - nmae: Install Node json
        uses: actions/setup-node@v3 
        with:  
          node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pakege-loc.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Build aplication
        run: npm run build
      - name: Deploy
        run: echo Deploying ...