name: Deploy React My App
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      # - name: Test aplication
        # run: npm run test
      # - name: Lint aplication
        # run: npm run lint
      - name: Build aplication
        run: npm run build
      - name: Deploy
        run: echo Deploying ...  